DROP TABLE TEST_TABLE1;

CREATE TABLE TEST_TABLE1(
	DATA1 NUMBER NOT NULL,
	DATA2 NUMBER NOT NULL
);

-- 컬럼 추가
ALTER TABLE TEST_TABLE1
ADD (DATA3 NUMBER NOT NULL);

-- 컬럼 데이터 타입 변경
ALTER TABLE TEST_TABLE1
MODIFY (DATA3 VARCHAR2(100));

-- 테이블 이름 변경
DROP TABLE TEST_TABLE2;

ALTER TABLE TEST_TABLE1
RENAME TO TEST_TABLE2;

-- 컬럼 이름 변경
ALTER TABLE TEST_TABLE2
RENAME COLUMN DATA3 TO DATA4;

-- 컬럼 삭제
ALTER TABLE TEST_TABLE2
DROP COLUMN DATA4;

-- 테이블 삭제
DROP TABLE TEST_TABLE2;