DROP TABLE EMP01;

CREATE TABLE EMP01
AS
SELECT * FROM EMP;

SELECT * FROM EMP01;

-- 사원들이 부서 번호를 40번으로 변경한다.
UPDATE EMP01
SET DEPTNO = 40;

-- 사원들의 입사일을 오늘로 변경한다.
UPDATE EMP01
SET HIREDATE = SYSDATE;

-- 사원들의 직무를 개발자로 변경한다.
UPDATE EMP01
SET JOB = '개발자';

-- 조건절 없으면 모든 로우 다바뀜

DROP TABLE EMP01;

CREATE TABLE EMP01
AS
SELECT * FROM EMP;

-- 사원들의 부서번호를 40, 입사일을 오늘, 직무를 개발자로 변경한다.
UPDATE EMP01
SET DEPTNO = 40,
	HIREDATE = SYSDATE,
	JOB = '개발자';
	
DROP TABLE EMP01;

CREATE TABLE EMP01
AS
SELECT * FROM EMP;

-- 10번 부서에 근무하고 있는 사원들을 40번 부서로 수정한다.
UPDATE EMP01
SET DEPTNO = 40
WHERE DEPTNO = 10;

SELECT * FROM EMP01;

-- SALESMAN 들의 입사일을 오늘, COMM을 2000으로 수정
UPDATE EMP01
SET HIREDATE = SYSDATE, COMM = 2000
WHERE JOB = 'SALESMAN';

-- 전체 사원의 평균 급여보다 낮은 사원들의 급여를 50% 인상한다.
UPDATE EMP01
SET SAL = SAL * 1.5
WHERE SAL < (SELECT AVG(SAL)
			FROM EMP);

SELECT AVG(SAL)
FROM EMP;

-- MANAGER 사원들의 직무를 Developer로 변경
UPDATE EMP01
SET JOB = 'Developer'
WHERE JOB = 'MANAGER';

-- 30번 부서에 근무하고 있는 사원들의 급여를 전체 평균 급여로 설정
UPDATE EMP01
SET SAL = (SELECT TRUNC(AVG(SAL))
			FROM EMP01)
WHERE DEPTNO = 30;

SELECT AVG(SAL)
FROM EMP01;

SELECT * FROM EMP01;

-- BLAKE 밑에서 근무하고 있는 사원들의 부서를 DALLAS 지역의 부서번호로 변경
UPDATE EMP01
SET DEPTNO = (SELECT DEPTNO
				FROM DEPT
				WHERE LOC = 'DALLAS')
WHERE MGR = (SELECT EMPNO
				FROM EMP01
				WHERE ENAME = 'BLAKE');

SELECT DEPTNO
FROM DEPT
WHERE LOC = 'DALLAS';

SELECT EMPNO
FROM EMP01
WHERE ENAME = 'BLAKE';

-- 20번 부서에 근무하고 있는 사원들의 직속상관을 KING으로 하고 급야를 전체급여의 최고액으로 설정한다.
UPDATE EMP01
SET MGR = (SELECT EMPNO
			FROM EMP01
			WHERE 'KING'),
	SAL = (SELECT MAX(SAL)
			FROM EMP01)
WHERE DEPTNO = 20;

SELECT EMPNO
FROM EMP01
WHERE 'KING';

SELECT MAX(SAL)
FROM EMP01;

DROP TABLE EMP01;

CREATE TABLE EMP01
AS
SELECT * FROM EMP;

-- 직무가 CLERK 인 사원들의 직무와 급여액을 20번 부서에 근무하고있는 사원 중
-- 급여 최고액을 받는 사원의 직무와 급여액으로 변경한다.
UPDATE EMP01
SET (JOB, SAL) = (SELECT JOB, SAL
					FROM EMP01
					WHERE SAL = (SELECT MAX(SAL)
								FROM EMP01))
WHERE JOB = 'CLERK';

SELECT JOB, SAL
FROM EMP01
WHERE SAL = (SELECT MAX(SAL)
			FROM EMP01);

SELECT MAX(SAL)
FROM EMP01;
