DROP TABLE TEST_TABLE100;

CREATE TABLE TEST_TABLE100 (
	DATA1 NUMBER CONSTRAINT TEST_TABLE100_PK PRIMARY KEY,
	DATA2 NUMBER NOT NULL
);

SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME 
FROM USER_IND_COLUMNS;
-- 오라클에서 primary key 컬럼은 자동으로 index 세팅됨

DROP TABLE EMP01;

CREATE TABLE EMP01 
AS
SELECT * FROM EMP;

SELECT * FROM EMP01;

INSERT INTO EMP01
SELECT * FROM EMP01;
-- 계속 insert 100만개 넘게 insert 진행

SELECT COUNT(*) FROM EMP01;

INSERT INTO EMP01 (ENAME)
VALUES ('홍길동');

SELECT * FROM EMP01
WHERE ENAME = '홍길동';
-- 0.1초 걸림

-- index 세팅
CREATE INDEX EMP01_IDX
ON EMP01(ENAME);
-- 만드는데 5초 걸림

SELECT * FROM EMP01
WHERE ENAME = '홍길동';
-- 인덱스 세팅 후 0.01 초 걸림
