-- 사원의 사원번호, 이름, 급여, 근무부서이름, 근무지역을 가지고 있는 뷰를 생성

DROP VIEW EMP_DEPT_VIEW;

CREATE VIEW EMP_DEPT_VIEW
AS
SELECT A1.EMPNO, A1.ENAME, A1.SAL, A2.DNAME, A2.LOC
FROM EMP A1, DEPT A2
WHERE A1.DEPTNO = A2.DEPTNO;

-- 뷰 생성 권한 설정
GRANT CREATE VIEW TO SCOTT;

-- 뷰 조회
SELECT * FROM EMP_DEPT_VIEW;

-- 테이블 생성
DROP TABLE EMP100;

CREATE TABLE EMP100
AS
SELECT * FROM EMP;

DROP TABLE DEPT100;

CREATE TABLE DEPT100
AS
SELECT * FROM DEPT;

CREATE VIEW EMP100_DEPT100_VIEW
AS
SELECT A1.EMPNO, A1.ENAME, A1.SAL, A2.DNAME, A2.LOC
FROM EMP100 A1, DEPT100 A2
WHERE A1.DEPTNO = A2.DEPTNO;

SELECT * FROM EMP100_DEPT100_VIEW;

-- 원본 테이블에 데이터 저장
INSERT INTO EMP100 (EMPNO, ENAME, SAL, DEPTNO)
VALUES (5000, '홍길동', 2000, 10);

SELECT * FROM EMP100;

SELECT * FROM EMP100_DEPT100_VIEW; -- 뷰에 반영됨

-- 뷰를 통해 데이터 저장
INSERT INTO EMP100_DPET100_VIEW (EMPNO, ENAME, SAL)
VALUES (6000, '김길동', 2000); -- 오류 발생
-- 2개의 테이블 조인해서 가져와서 오류 발생하는 거 
-- 조인된 테이블 뷰를 통해 insert, delete 안됨

CREATE VIEW EMP200_VIEW
AS
SELECT EMPNO, ENAME, SAL
FROM EMP100;

INSERT INTO EMP200_VIEW (EMPNO, ENAME, SAL)
VALUES (7000, '박길동', 3000); -- 오류 발생 x

SELECT * FROM EMP100; -- 반영되어 있음
