DROP TABLE TEST_TABLE1;

CREATE TABLE TEST_TABLE1(
	DATA1 NUMBER NOT NULL,
	DATA2 NUMBER NOT NULL
);
-- 테이블은 생성/삭제는 물리적 디스크에 반영

INSERT INTO TEST_TABLE1 (DATA1, DATA2)
VALUES (100, 200);
-- 트랜잭션 진행 중 => 물리적 디스크에 반영 x

COMMIT; -- 물리적 디스크에 반영됨, 트랜잭션 종료

-- 트랜잭션 시작
INSERT INTO TEST_TABLE1 (DATA1, DATA2)
VALUES (101, 201);

UPDATE TEST_TABLE1
SET DATA2=2000
WHERE DATA1=100;

DELETE FROM TEST_TABLE1;

ROLLBACK; -- 트랜잭션 진행 전으로 돌아감

-- 트랜잭션 시작
INSERT INTO TEST_TABLE1 (DATA1, DATA2)
VALUES (103, 203);

SAVEPOINT P1; -- 저장점

INSERT INTO TEST_TABLE1
VALUES (104, 204);

ROLLBACK TO P1; -- SAVEPOINT 시점으로 돌아감

ROLLBACK; -- 트랜잭션 시작으로 돌아감