DROP TABLE TEST_TABLE20;

CREATE TABLE TEST_TABLE20(
	DATA1 NUMBER,
	DATA2 NUMBER,
	DATA3 NUMBER,
	DATA4 NUMBER,
	DATA5 NUMBER,
	DATA6 NUMBER
);

-- NULL 제약조건 추가
ALTER TABLE TEST_TABLE20 
MODIFY DATA1 NOT NULL;

INSERT INTO TEST_TABLE20 (DATA1)
VALUES (NULL); -- 오류

-- PRIMARY KEY 제약조건 추가
ALTER TABLE TEST_TABLE20
ADD CONSTRAINT TEST_TABLE20_DATA2_PK PRIMARY KEY(DATA2);

INSERT INTO TEST_TABLE20 (DATA1, DATA2)
VALUES (1, 10);

INSERT INTO TEST_TABLE20 (DATA1, DATA2)
VALUES (2, 10); -- 제약조건 위배

INSERT INTO TEST_TABLE20 (DATA1, DATA2)
VALUES (3, NULL); -- 제약조건 위배

-- 외래키 제약조건 추가
ALTER TABLE TEST_TABLE20
ADD CONSTRAINT TEST_TABLE20_DATA3_FK FOREIGN KEY(DATA3)
									REFERENCES EMP(EMPNO);
									
INSERT INTO TEST_TABLE20 (DATA1, DATA2, DATA3)
VALUES (10, 100, 7369); 

INSERT INTO TEST_TABLE20 (DATA1, DATA2, DATA3)
VALUES (11, 101, 100); -- 제약조건 위배

-- UNIQUE 제약조건 추가
ALTER TABLE TEST_TABLE20
ADD CONSTRAINT TEST_TABLE20_DATA4_UK UNIQUE(DATA4);

INSERT INTO TEST_TABLE20 (DATA1, DATA2, DATA4)
VALUES (12, 102, 100);

INSERT INTO TEST_TABLE20 (DATA1, DATA2, DATA4)
VALUES (13, 103, 100); -- 제약조건 위배

-- CHECK 제약조건 추가
ALTER TABLE TEST_TABLE20
ADD CONSTRAINT TEST_TABLE20_DATA5_CK CHECK(DATA5 BETWEEN 1 AND 10);

INSERT INTO TEST_TABLE20 (DATA1, DATA2, DATA5)
VALUES (14, 104, 5);

INSERT INTO TEST_TABLE20 (DATA1, DATA2, DATA5)
VALUES (15, 105, 20); -- 제약조건 위배

ALTER TABLE TEST_TABLE20
ADD CONSTRAINT TEST_TABLE20_DATA6_CK CHECK(DATA6 IN(10, 20, 30));

INSERT INTO TEST_TABLE20 (DATA1, DATA2, DATA6)
VALUES (16, 106, 10);

INSERT INTO TEST_TABLE20 (DATA1, DATA2, DATA6)
VALUES (16, 106, 50); -- 제약조건 위배

SELECT * FROM TEST_TABLE20;

-- 제약족너 제거
DROP TABLE TEST_TABLE30;

CREATE TABLE TEST_TABLE30(
	DATA1 NUMBER NOT NULL,
	DATA2 NUMBER CONSTRAINT TEST_TABLE30_DATA2_PK PRIMARY KEY,
	DATA3 NUMBER CONSTRAINT TEST_TABLE30_DATA3_FK
				REFERENCES EMP(EMPNO),
	DATA4 NUMBER CONSTRAINT TEST_TABLE30_DATA4_UK UNIQUE,
	DATA5 NUMBER CONSTRAINT TEST_TABLE30_DATA5_CK 
				CHECK (DATA5 BETWEEN 1 AND 10),
	DATA6 NUMBER CONSTRAINT TEST_TABLE30_DATA6_CK
				CHECK (DATA6 IN (10, 20, 30)
);

-- NOT NULL 제약 조건 수정
ALTER TABLE TEST_TABLE30
MODIFY DATA1 NULL;

INSERT INTO TEST_TABLE30 (DATA1, DATA2)
VALUES (NULL, 100);

-- PRIMARY KEY 제약 조건 제거
ALTER TABLE TEST_TABLE30
DROP CONSTRAINT TEST_TABLE30_DATA3_PK;

INSERT INTO TEST_TABLE30 (DATA1, DATA2)
VALUES (NULL, NULL);

-- 외래키 제약 조건 제거
ALTER TABLE TEST_TABLE30
DROP CONSTRAINT TEST_TABLE30_DATA3_FK;

INSERT INTO TEST_TABLE30 (DATA3)
VALUES (1000);

-- UNIQUE 제약 조건 제거
ALTER TABLE TEST_TABLE30
DROP CONSTRAINT TEST_TABLE30_DATA4_UK;

INSERT INTO TEST_TABLE30 (DATA4)
VALUES (100);

INSERT INTO TEST_TABLE30 (DATA4)
VALUES (100);

-- CHECK 제약 조건 제거
ALTER TABLE TEST_TABLE30
DROP CONSTRAINT TEST_TABLE30_DATA5_CK;

ALTER TABLE TEST_TABLE30
DROP CONSTRAINT TEST_TABLE30_DATA6_CK;

INSERT INTO TEST_TABLE30 (DATA5, DATA6)
VALUES (20, 100);

SELECT * FROM TEST_TABLE30;

-- 제약조건 활성화 / 비활성화
DROP TABLE TEST_TABLE40;

CREATE TABLE TEST_TABLE40 (
	DATA1 NUMBER CONSTRAINT TEST_TABLE40_DATA1_PK PRIMARY KEY
);

INSERT INTO TEST_TABLE40 (DATA1)
VALUES (100);

INSERT INTO TEST_TABLE40 (DATA1)
VALUES (100); -- 제약조건 위배

-- 비활성화
ALTER TABLE TEST_TABLE40
DISABLE CONSTRAINT TEST_TABLE40_DATA1_PK;

INSERT INTO TEST_TABLE40 (DATA1)
VALUES (100); 

SELECT * FROM TEST_TABLE40;

-- 활성화
ALTER TABLE TEST_TABLE40
ENABLE CONSTRAINT TEST_TABLE40_DATA1_PK; -- 안됨

DELETE FROM TEST_TABLE40;

INSERT INTO TEST_TABLE40 (DATA1)
VALUES (100); 

INSERT INTO TEST_TABLE40 (DATA1)
VALUES (200); 

ALTER TABLE TEST_TABLE40
ENABLE CONSTRAINT TEST_TABLE40_DATA1_PK; 

INSERT INTO TEST_TABLE40 (DATA1)
VALUES (100); -- 제약조건 위배
